### ISSUE TITLE
Clearing logs breaks extension

### ISSUE THREAD

**Issue by mmmols** [relayjs/relay-devtools#92]
Whenever I clear logs, it stops working. The only way to get it to work again is to close the chrome devtools on open it again. 

Also, I'm quite confused about what to except to get from this extension? The reason being, the preview images shops a cool store explorer and I'm not seeing this at all. So I wonder if it's on my part? 

I tried to see if I could catch some errors in Inspect views from your extensions console - but nothing.

I use relay v9.0.0. 

Chrome version: 84.0.4147.105
Extension version ab56cb5 (3/13/2020)

**Comment by dadapoof** [comment]
Hi @mmmols, thanks for reaching out! Yeah, so thats a pretty old version of the devtools. I'm sorry that you're experiencing issues with that version. I have some good news and some bad news. The good news is that I've been working on the dev tools for the past several weeks and I'm in the process of releasing a new version to the chrome store. The bad news is that you might not get that extension for a little while because the chrome store's review process takes some time.
Hope this helps!

**Comment by dadapoof** [comment]
Hi @mmmols, just following up here. The extension was just released to the chrome store. Check it out and let me know if you have any more issues seeing it!

**Comment by mmmols** [comment]
Hi @dadapoof 

Thank you for the update. Much appreciated - especially the event logger and store explorer 🎉. 

Tho, I'm experiencing an issue with refreshing my app while having devtools open and all request afterwards doesn't appear in relay devtools. The only way to make it work again, is to close and reopen the chrome devtool. Let me know, if I should create another issue. 

Again, thanks for all your work man!!

**Comment by dadapoof** [comment]
@mmmols, thanks for catching that! Yeah its a known bug that has just been fixed internally -- the fix will come with the next chrome store release (should be around next week). For now, I think sadly the only way to make it work is indeed by closing and re-opening the dev tools. You can also inspect the relay dev tools and refresh that panel but I think it's basically the same. Thanks again for your feedback! 😄
